# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    # Milestone "0 Closed Beta"
    milestone: 3

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    label:
      - "dependencies"
    # Milestone "0 Closed Beta"
    milestone: 3

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    label:
      - "dependencies"
    # Milestone "0 Closed Beta"
    milestone: 3
    versioning-strategy: "increase"
