AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.0

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

require:
  - rubocop-performance
  - rubocop-rails
