AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  TargetRailsVersion: 6.0

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
Layout/LineLength:
  Max: 80

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
