AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  TargetRailsVersion: 6.1

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
Layout/LineLength:
  Max: 80

# This is a conceptional demo app for nested namespaces. So there is no need
# to have proper localization.
Rails/I18nLocaleTexts:
  Enabled: false

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
