sudo: false

language: ruby

cache: bundler

rvm:
  - 2.2

env:
  - DB=sqlite

before_script:
  - gem install brakeman
  - bin/rake db:setup RAILS_ENV=test

script:
  - RAILS_ENV=test bin/rake --trace db:migrate test
  - bundle exec rake assets:precompile RAILS_ENV=test
  - brakeman -z -4
