sudo: false

language: ruby

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

rvm:
  - 2.6.5

env:
  - DB=sqlite

before_install:
  - gem --version
  - gem update bundler
  - bundle --version

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

before_script:
  - bundle exec rails version
  - RAILS_ENV=test bundle exec rails db:migrate

script:
  - RAILS_ENV=test bundle exec rake --trace ci
  - RAILS_ENV=test bundle exec rails assets:precompile
  - gem install brakeman
  - brakeman -z -5
