sudo: false

language: ruby

cache: bundler

rvm:
  - 2.6.5

env:
  - DB=sqlite

before_install:
  - gem update --system
  - gem --version
  - gem update bundler
  - bundle --version
  - bundle update --bundler
  - bundler --version

before_script:
  - bundle exec rails version
  - RAILS_ENV=test bundle exec rails db:migrate
  - RAILS_ENV=test bundle exec rails db:migrate:status

script:
  - RAILS_ENV=test bundle exec rake --trace ci
  - RAILS_ENV=test bundle exec rails assets:precompile
  - gem install brakeman
  - brakeman -z -5
