# This setup is based on: https://github.com/evilmartians/ruby-on-whales

x-app: &app
  build:
    context: .
    args:
      RUBY_VERSION: '3.2.0'
      NODE_MAJOR: '18'
      # The purpose of this variable is to force a rebuild of the image.
      NODE_FULL_VERSION: '18.13.0'
      YARN_VERSION: '1.22.19'
  # We need to update the version number of the image each time
  # we update any of the variables above.
  image: crud-base:2.2.0
  environment: &env
    NODE_ENV: ${NODE_ENV:-development}
    RAILS_ENV: ${RAILS_ENV:-development}
  tmpfs:
    - /tmp
    - /app/tmp/pids

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - ..:/app:cached
    - bundle:/usr/local/bundle
    - rails_cache:/app/tmp/cache
    - node_modules:/app/node_modules
    - assets:/app/public/assets
    - history:/usr/local/hist
    - ./.bashrc:/root/.bashrc:ro
  environment: &backend_environment
    <<: *env
    MALLOC_ARENA_MAX: 2
    WEB_CONCURRENCY: ${WEB_CONCURRENCY:-1}
    BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
    XDG_DATA_HOME: /app/tmp/cache
    YARN_CACHE_FOLDER: /app/node_modules/.yarn-cache
    HISTFILE: /usr/local/hist/.bash_history
    IRB_HISTFILE: /usr/local/hist/.irb_history
    EDITOR: vi

services:
  rails:
    <<: *backend
    command: bundle exec rails

  web:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'
    depends_on:
      css_watcher:
        condition: service_started
      js_watcher:
        condition: service_started

  css_watcher:
    <<: *backend
    command: yarn build:css --watch
    volumes:
      - ..:/app:cached
      - node_modules:/app/node_modules
    environment:
      <<: *env
      YARN_CACHE_FOLDER: /app/node_modules/.yarn-cache

  js_bundling:
    <<: *backend
    command: yarn build
    volumes:
      - ..:/app:cached
      - node_modules:/app/node_modules
    environment:
      <<: *env
      YARN_CACHE_FOLDER: /app/node_modules/.yarn-cache

  js_watcher:
    <<: *backend
    command: yarn build --watch
    volumes:
      - ..:/app:cached
      - node_modules:/app/node_modules
    environment:
      <<: *env
      YARN_CACHE_FOLDER: /app/node_modules/.yarn-cache

volumes:
  assets:
  bundle:
  node_modules:
  history:
  rails_cache:
