---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '15 3 * * 1'
jobs:
  static-analysis:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Ruby"
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: "Check the environment"
        run: |
          ruby --version
          gem --version
          bundle --version
      - name: "Install dependencies"
        run: |
          bundle install --jobs 4 --retry 3
          bundle exec rails version
      - name: "Run the static analysis"
        run: "RAILS_ENV=test bundle exec rails ci"
  brakeman:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Ruby"
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: "Install dependencies"
        run: "gem install brakeman"
      - name: "Run the security checker"
        run: "brakeman -z -6"
